shared-chart:
  name: shared-chart
  namespace: shared-services

  deployment:
    annotations: {}
    image: ghcr.io/mohamedalaaelsafy/jenkins-dockerfile:latest
    tag: latest
    restartPolicy: Always
    serviceAccountName: tsf-prod
    resources:
      requests:
        cpu: 30m
        memory: 10Mi
      limits:
        cpu: 100m
        memory: 300Mi
    ports:
    - name: http-port
      containerPort: 8080
    - name: jnlp-port
      containerPort: 50000
    env:
    - name: NODE_ENV
      value: production
    - name: MICROSERVICE_NAME
      value: admin
    volumeMounts:
    - name: jenkins-data
      mountPath: /var/jenkins_home
    - name: docker-socket
      mountPath: /var/run/docker.sock
    volumes:
    - name: jenkins-data
      persistentVolumeClaim:
        claimName: jenkins-pvc
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock

service:
  annotations: {}
  name: jenkins-svc
  labels: {}
  selector:
    app: jenkins  
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-port



pvc:
- name: jenkins-pvc
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi


ingress:
  name: jenkins
  annotations: {}
  ingressClassName: nginx
  rules:
    - host: jenkins.com
      paths:
        - path: /
          service: jenkins-svc
          port: 8080
