{{- if .Values.pvc }}
{{- range $value := .Values.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $.Values.namespace | lower }}
  name: {{ $value.name }}
spec:
  storageClassName: {{ $value.storageClass | default "ssd" }}
  accessModes:
    - {{ $value.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $value.storage | default "50Gi" }}
---
{{- end }}
{{- end }}