{{- if .Values.secret }}
{{- range $value := .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $value.name }}
data:
{{- toYaml $value.data | nindent 2 }}
---
{{- end }}
{{- end }}
